//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class acctmast
    {
        public int recordno { get; set; }
        public string agency { get; set; }
        public string acct { get; set; }
        public string acctname { get; set; }
        public bool dropdown { get; set; }
        public string acctaddr1 { get; set; }
        public string acctaddr2 { get; set; }
        public string acctaddr3 { get; set; }
        public string acctaddr4 { get; set; }
        public Nullable<int> axisitenbr { get; set; }
        public string parentacct { get; set; }
        public Nullable<bool> ChangeMgmt { get; set; }
        public int SGroupNbr { get; set; }
        public bool AutoCreateUsers { get; set; }
        public int ReasSetNbr { get; set; }
        public byte ExpTAPurge { get; set; }
        public int DefaultOrgKey { get; set; }
        public int UdidSetNbr { get; set; }
        public int GicCode { get; set; }
        public string AcctCat1 { get; set; }
        public string AcctCat2 { get; set; }
        public string AcctCat3 { get; set; }
        public string AcctCat4 { get; set; }
        public string AcctCat5 { get; set; }
        public string AcctCat6 { get; set; }
        public string AcctCat7 { get; set; }
        public string AcctCat8 { get; set; }
        public byte acctType { get; set; }
    }
}
