//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class airports
    {
        public int recordno { get; set; }
        public string airport { get; set; }
        public string rrcarrier { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string mode { get; set; }
        public string metro { get; set; }
        public string country { get; set; }
        public string region { get; set; }
        public string CtryCode { get; set; }
        public string RegionCode { get; set; }
        public decimal longitude { get; set; }
        public decimal latitude { get; set; }
        public string airportnam { get; set; }
    }
}
