//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class bcstrptinstance
    {
        public int bcstikey { get; set; }
        public string bcstrkey { get; set; }
        public string agency { get; set; }
        public string rptfilepath { get; set; }
        public bool rptactive { get; set; }
        public string outputtype { get; set; }
        public int viewcount { get; set; }
        public System.DateTime rptdate { get; set; }
        public int batchnum { get; set; }
        public int processkey { get; set; }
        public bool authreqd { get; set; }
        public string authid { get; set; }
        public string authpw { get; set; }
    }
}
