//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class broadcast_servers
    {
        public int id { get; set; }
        public int server_number { get; set; }
        public int server_function_id { get; set; }
    
        public virtual broadcast_server_function broadcast_server_function { get; set; }
    }
}
