//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class broadcast_stage_agencies
    {
        public int id { get; set; }
        public string agency { get; set; }
        public bool currently_staged { get; set; }
        public string staged_batchnumber { get; set; }
    
        public virtual mstragcy mstragcy { get; set; }
    }
}
