//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;

namespace iBank.Services.Orm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CISMasterEntities : DbContext
    {
        public CISMasterEntities()
            : base("name=CISMasterEntities")
        {
            var isOfflineServer = ConfigurationManager.AppSettings["IsOfflineServer"];

            if (isOfflineServer != null && isOfflineServer.ToUpper() == "TRUE")
            {
                //we don't want a time limit for reports that are already running as offline reports
                ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 0;
            }
            else
            {
                ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 60;
            }
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AirMileage> AirMileages { get; set; }
    }
}
