//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class collist2
    {
        public short sortord { get; set; }
        public string colname { get; set; }
        public string advcolname { get; set; }
        public string bigname { get; set; }
        public short collngth { get; set; }
        public string coltable { get; set; }
        public string coltype { get; set; }
        public string rpttype { get; set; }
        public string head1 { get; set; }
        public string head2 { get; set; }
        public bool advoption { get; set; }
        public bool subtotal { get; set; }
        public bool islookup { get; set; }
        public string lookuptbl { get; set; }
        public string fnlookup { get; set; }
        public bool inactive { get; set; }
        public string usage { get; set; }
        public string agency { get; set; }
        public string coltag { get; set; }
        public bool travFilter { get; set; }
        public string tWheretype { get; set; }
        public string tluTable { get; set; }
        public string tluCodeCol { get; set; }
        public string tluDescCol { get; set; }
        public bool tluPkList { get; set; }
        public string tDbSource { get; set; }
        public short tSort1 { get; set; }
        public short tSort2 { get; set; }
        public string webvarname { get; set; }
        public bool tlsonly { get; set; }
        public bool v5only { get; set; }
    }
}
