//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public int RecordNo { get; set; }
        public string LangCode { get; set; }
        public string NumCtryCod { get; set; }
        public string CtryCode { get; set; }
        public string CtryName { get; set; }
        public string FlagImage { get; set; }
        public string fcRegnCode { get; set; }
        public string regionCode { get; set; }
        public decimal longitude { get; set; }
        public decimal latitude { get; set; }
        public string ctryCode2 { get; set; }
    }
}
