//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class curcountry
    {
        public int recordno { get; set; }
        public string country { get; set; }
        public string curcode { get; set; }
        public string csymbol { get; set; }
        public string cleftright { get; set; }
        public string cdecimal { get; set; }
        public string cthousands { get; set; }
        public bool inactive { get; set; }
        public string numcurcode { get; set; }
        public string CountryName { get; set; }
        public string CtryCode { get; set; }
    }
}
