//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class eProfiles
    {
        public int eProfileNo { get; set; }
        public string profilename { get; set; }
        public string profiledesc { get; set; }
        public string agency { get; set; }
        public int tradingPartNo { get; set; }
        public int mappingcard { get; set; }
        public bool directDelivery { get; set; }
        public string fileNameMask { get; set; }
        public bool ZipOutput { get; set; }
    }
}
