//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class hibcar
    {
        public int recordno { get; set; }
        public string agency { get; set; }
        public int reckey { get; set; }
        public string company { get; set; }
        public string autocity { get; set; }
        public string autostat { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<System.DateTime> rentdate { get; set; }
        public string cartype { get; set; }
        public string reascoda { get; set; }
        public Nullable<decimal> abookrat { get; set; }
        public Nullable<decimal> compamt { get; set; }
        public Nullable<decimal> aexcprat { get; set; }
        public string milecost { get; set; }
        public string ratetype { get; set; }
        public Nullable<short> cplusmin { get; set; }
        public Nullable<decimal> ccommisn { get; set; }
        public string citycode { get; set; }
        public string carcode { get; set; }
        public Nullable<int> numcars { get; set; }
        public string confirmno { get; set; }
        public Nullable<bool> invbyagcy { get; set; }
        public string CarSvgCode { get; set; }
        public decimal CarStdRate { get; set; }
        public string CarTranTyp { get; set; }
        public string MoneyType { get; set; }
        public Nullable<System.DateTime> DateBack { get; set; }
        public Nullable<int> seqno { get; set; }
        public string carCtryCod { get; set; }
        public string carVendCod { get; set; }
        public string carBkType { get; set; }
        public Nullable<short> smartCtrC { get; set; }
        public string comisableC { get; set; }
        public string carRateTyp { get; set; }
        public string carSegStat { get; set; }
        public Nullable<System.DateTime> carVoidDat { get; set; }
        public Nullable<int> trdTrxNumC { get; set; }
        public string pickcitycd { get; set; }
        public string dropcitycd { get; set; }
        public Nullable<short> carsegnum { get; set; }
    }
}
