//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class hibhotel
    {
        public int recordno { get; set; }
        public string agency { get; set; }
        public int reckey { get; set; }
        public string chaincod { get; set; }
        public string hotelnam { get; set; }
        public string metro { get; set; }
        public string hotcity { get; set; }
        public string hotstate { get; set; }
        public Nullable<short> nights { get; set; }
        public Nullable<short> rooms { get; set; }
        public Nullable<short> numguests { get; set; }
        public Nullable<System.DateTime> datein { get; set; }
        public Nullable<decimal> bookrate { get; set; }
        public Nullable<decimal> compamt { get; set; }
        public string moneytype { get; set; }
        public string roomtype { get; set; }
        public Nullable<decimal> hexcprat { get; set; }
        public string guarante { get; set; }
        public string reascodh { get; set; }
        public Nullable<short> hplusmin { get; set; }
        public Nullable<decimal> hcommissn { get; set; }
        public string hotphone { get; set; }
        public string confirmno { get; set; }
        public Nullable<bool> invbyagcy { get; set; }
        public string HotSvgCode { get; set; }
        public decimal HotStdRate { get; set; }
        public string HotTranTyp { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public string HotelAddr1 { get; set; }
        public string HotelAddr2 { get; set; }
        public string HotelZip { get; set; }
        public string HotCountry { get; set; }
        public Nullable<int> seqno { get; set; }
        public string hotPropID { get; set; }
        public int chid { get; set; }
        public string source { get; set; }
        public string hotCtryCod { get; set; }
        public string hotCityCod { get; set; }
        public string hotVendCod { get; set; }
        public string hotBkType { get; set; }
        public Nullable<short> smartCtrH { get; set; }
        public string comisableH { get; set; }
        public string hotRateTyp { get; set; }
        public string hotSegStat { get; set; }
        public Nullable<System.DateTime> hotVoidDat { get; set; }
        public Nullable<int> trdTrxNumH { get; set; }
    }
}
