//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class hibSvcFee
    {
        public int recordno { get; set; }
        public string agency { get; set; }
        public string recloc { get; set; }
        public System.DateTime trandate { get; set; }
        public string acct { get; set; }
        public string passlast { get; set; }
        public string passfrst { get; set; }
        public decimal svcfee { get; set; }
        public string descript { get; set; }
        public string invoice { get; set; }
        public string mco { get; set; }
        public string cardnum { get; set; }
        public string trantype { get; set; }
        public string sourceabbr { get; set; }
        public string corpacct { get; set; }
        public string MoneyType { get; set; }
        public decimal Tax1 { get; set; }
        public decimal Tax2 { get; set; }
        public decimal Tax3 { get; set; }
        public decimal Tax4 { get; set; }
        public string IATANbr { get; set; }
    }
}
