//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class hibtrip
    {
        public string agency { get; set; }
        public int reckey { get; set; }
        public string recloc { get; set; }
        public string branch { get; set; }
        public string pseudocity { get; set; }
        public string agentid { get; set; }
        public string acct { get; set; }
        public string invoice { get; set; }
        public Nullable<System.DateTime> invdate { get; set; }
        public Nullable<System.DateTime> bookdate { get; set; }
        public string trantype { get; set; }
        public string domintl { get; set; }
        public string ticket { get; set; }
        public string passlast { get; set; }
        public string passfrst { get; set; }
        public string break1 { get; set; }
        public string break2 { get; set; }
        public string break3 { get; set; }
        public string break4 { get; set; }
        public Nullable<decimal> airchg { get; set; }
        public string credcard { get; set; }
        public string cardnum { get; set; }
        public Nullable<decimal> stndchg { get; set; }
        public Nullable<System.DateTime> depdate { get; set; }
        public string valcarr { get; set; }
        public Nullable<decimal> mktfare { get; set; }
        public Nullable<System.DateTime> arrdate { get; set; }
        public Nullable<decimal> offrdchg { get; set; }
        public string reascode { get; set; }
        public Nullable<short> plusmin { get; set; }
        public Nullable<decimal> svcfee { get; set; }
        public Nullable<decimal> acommisn { get; set; }
        public Nullable<decimal> basefare { get; set; }
        public Nullable<decimal> faretax { get; set; }
        public string savingcode { get; set; }
        public string tourcode { get; set; }
        public string tickettype { get; set; }
        public Nullable<bool> exchange { get; set; }
        public string origticket { get; set; }
        public Nullable<decimal> tax1 { get; set; }
        public Nullable<decimal> tax2 { get; set; }
        public Nullable<decimal> tax3 { get; set; }
        public Nullable<decimal> tax4 { get; set; }
        public string sourceabbr { get; set; }
        public string corpacct { get; set; }
        public string IATANbr { get; set; }
        public string MoneyType { get; set; }
        public Nullable<System.DateTime> TripStart { get; set; }
        public Nullable<System.DateTime> TripEnd { get; set; }
        public string TkAgent { get; set; }
        public string BkAgent { get; set; }
        public string BkTool { get; set; }
        public Nullable<int> llRecno { get; set; }
        public string valcarMode { get; set; }
        public string origValCar { get; set; }
        public string bkSource { get; set; }
        public string gds { get; set; }
        public string travelerID { get; set; }
        public string ccNumber2 { get; set; }
    }
}
