//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iBankAdministrationEntities : DbContext
    {
        public iBankAdministrationEntities()
            : base("name=iBankAdministrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SvrStatus> SvrStatus { get; set; }
        public virtual DbSet<broadcast_server_function> broadcast_server_function { get; set; }
        public virtual DbSet<broadcast_servers> broadcast_servers { get; set; }
        public virtual DbSet<report_server_function> report_server_function { get; set; }
        public virtual DbSet<report_servers> report_servers { get; set; }
        public virtual DbSet<ibank_feature_flag> ibank_feature_flag { get; set; }
    }
}
