//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class iBankDatabases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public iBankDatabases()
        {
            this.report_server_stage = new HashSet<report_server_stage>();
            this.report_rollout_stage = new HashSet<report_rollout_stage>();
        }
    
        public string databasename { get; set; }
        public short servernbr { get; set; }
        public bool replicated { get; set; }
        public bool active { get; set; }
        public bool StopLoad { get; set; }
        public bool StopBcst { get; set; }
        public short control1 { get; set; }
        public short control2 { get; set; }
        public bool StopMsgsvr { get; set; }
        public string historyLodSvr { get; set; }
        public string previewLodSvr { get; set; }
        public string resMarkLodSvr { get; set; }
        public string CCDataLodSvr { get; set; }
        public string TTrackerLodSvr { get; set; }
        public string server_address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_server_stage> report_server_stage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_rollout_stage> report_rollout_stage { get; set; }
    }
}
