//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class iBankServers
    {
        public string ServerName { get; set; }
        public short ServerNbr { get; set; }
        public string SQLHome { get; set; }
        public string BulkDirectory { get; set; }
        public string SQLDrive { get; set; }
        public string UNCPath { get; set; }
    }
}
