//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ibbatch
    {
        public int UserNumber { get; set; }
        public string agency { get; set; }
        public int batchnum { get; set; }
        public string batchname { get; set; }
        public string emailaddr { get; set; }
        public string acctlist { get; set; }
        public Nullable<int> prevhist { get; set; }
        public Nullable<int> weekmonth { get; set; }
        public Nullable<int> monthstart { get; set; }
        public Nullable<int> monthrun { get; set; }
        public Nullable<int> weekstart { get; set; }
        public Nullable<int> weekrun { get; set; }
        public Nullable<System.DateTime> nxtdstart { get; set; }
        public Nullable<System.DateTime> nxtdend { get; set; }
        public Nullable<System.DateTime> lastrun { get; set; }
        public Nullable<System.DateTime> lastdstart { get; set; }
        public Nullable<System.DateTime> lastdend { get; set; }
        public bool errflag { get; set; }
        public bool runspcl { get; set; }
        public Nullable<System.DateTime> spclstart { get; set; }
        public Nullable<System.DateTime> spclend { get; set; }
        public Nullable<int> pagebrklvl { get; set; }
        public string titleacct { get; set; }
        public string bcsenderemail { get; set; }
        public string bcsendername { get; set; }
        public Nullable<System.DateTime> nextrun { get; set; }
        public string setby { get; set; }
        public string holdrun { get; set; }
        public Nullable<int> reportdays { get; set; }
        public Nullable<int> rptusernum { get; set; }
        public Nullable<bool> usespcl { get; set; }
        public Nullable<bool> nodataoptn { get; set; }
        public string emailsubj { get; set; }
        public string mailformat { get; set; }
        public string outputtype { get; set; }
        public bool displayuid { get; set; }
        public string outputdest { get; set; }
        public int eProfileNo { get; set; }
        public string emailccadr { get; set; }
        public string LangCode { get; set; }
        public byte RunNewData { get; set; }
        public int fystartmo { get; set; }
        public string timezone { get; set; }
        public double gmtdiff { get; set; }
        public string unilangcode { get; set; }
        public bool send_error_email { get; set; }
    }
}
