//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ibproces
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ibproces()
        {
            this.report_rollout_stage = new HashSet<report_rollout_stage>();
        }
    
        public int processkey { get; set; }
        public string rpttype { get; set; }
        public string caption { get; set; }
        public string pgmname { get; set; }
        public string usage { get; set; }
        public bool bcactive { get; set; }
        public string rptname { get; set; }
        public Nullable<int> reclimit { get; set; }
        public string purpose { get; set; }
        public string longdesc { get; set; }
        public string v4caption { get; set; }
        public string traveltype { get; set; }
        public bool visible { get; set; }
        public int rptrank { get; set; }
        public bool dotnet { get; set; }
        public bool report_can_be_translated { get; set; }
        public bool staged { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_rollout_stage> report_rollout_stage { get; set; }
    }
}
