//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ibreascd
    {
        public int recordno { get; set; }
        public string agency { get; set; }
        public string reascode { get; set; }
        public string reasdesc { get; set; }
        public string parentAcct { get; set; }
        public int ReasSetNbr { get; set; }
        public string LangCode { get; set; }
        public string LongDesc { get; set; }
        public string ExtendDesc { get; set; }
    }
}
