//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ibRptLog
    {
        public System.DateTime rptdate { get; set; }
        public string agency { get; set; }
        public string userid { get; set; }
        public string username { get; set; }
        public string rptprogram { get; set; }
        public int rptlogno { get; set; }
        public Nullable<int> numrecords { get; set; }
        public Nullable<int> numseconds { get; set; }
        public string rptmode { get; set; }
        public Nullable<int> usernumber { get; set; }
        public string iBankVer { get; set; }
        public int processkey { get; set; }
        public System.DateTime submittime { get; set; }
        public System.DateTime starttime { get; set; }
        public byte svrnbr { get; set; }
        public string rptstatus { get; set; }
    }
}
