//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ibRptLogSQL
    {
        public int RecordNo { get; set; }
        public int RptLogNo { get; set; }
        public int UserNumber { get; set; }
        public string UserID { get; set; }
        public int Processkey { get; set; }
        public int UDRKey { get; set; }
        public int SavedRptKey { get; set; }
        public string SQLText { get; set; }
        public System.DateTime LogDate { get; set; }
    }
}
