//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ibRptLogCrit
    {
        public int recordno { get; set; }
        public int rptlogno { get; set; }
        public string varname { get; set; }
        public string varvalue { get; set; }
        public bool advoptn { get; set; }
        public string varoper { get; set; }
    }
}
