//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ibudid
    {
        public int recordno { get; set; }
        public string agency { get; set; }
        public int reckey { get; set; }
        public string recloc { get; set; }
        public Nullable<short> udidno { get; set; }
        public string udidtext { get; set; }
    }
}
