//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ibUserMacroRpt
    {
        public int recordno { get; set; }
        public int macrokey { get; set; }
        public string agency { get; set; }
        public int usernumber { get; set; }
        public int processkey { get; set; }
        public int udrkey { get; set; }
    }
}
