//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ibwhcrit
    {
        public int ibwcritkey { get; set; }
        public string webvarname { get; set; }
        public string caption { get; set; }
        public string wheretype { get; set; }
        public bool inactive { get; set; }
        public string critType { get; set; }
        public string filterType { get; set; }
        public short dependsOn { get; set; }
        public string luTable { get; set; }
        public string luCodeCol { get; set; }
        public string luDescCol { get; set; }
        public bool luPkLst { get; set; }
        public string dbSource { get; set; }
        public short sort1 { get; set; }
        public short sort2 { get; set; }
    }
}
