//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class intlparm
    {
        public int RecordNo { get; set; }
        public string LangCode { get; set; }
        public string country { get; set; }
        public string csymbol { get; set; }
        public string cleftright { get; set; }
        public string cdecimal { get; set; }
        public string dateformat { get; set; }
        public string datemark { get; set; }
        public string datedisplay { get; set; }
        public string CtryDesc { get; set; }
    }
}
