//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageTags
    {
        public int TagNo { get; set; }
        public string ShortDesc { get; set; }
        public string TagType { get; set; }
        public string Context { get; set; }
        public byte MaxChars { get; set; }
        public string VarName { get; set; }
        public byte NbrLines { get; set; }
    }
}
