//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class metro
    {
        public int RecordNo { get; set; }
        public string metrocode { get; set; }
        public string metrocity { get; set; }
        public string metrostate { get; set; }
        public string CtryCode { get; set; }
    }
}
