//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class miscparams
    {
        public int recordno { get; set; }
        public string parmcat { get; set; }
        public string parmcode { get; set; }
        public string parmdesc { get; set; }
        public string LangCode { get; set; }
        public short DisplayOrd { get; set; }
    }
}
