//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstrAgcySources
    {
        public string SourceAbbr { get; set; }
        public string agency { get; set; }
        public bool ConvertHistCurr { get; set; }
        public string backoffice { get; set; }
        public string ibdcversion { get; set; }
        public string currcode { get; set; }
        public string SourceDesc { get; set; }
        public string HomeCtry { get; set; }
        public string BaseCurr { get; set; }
        public Nullable<System.DateTime> lastHistLd { get; set; }
        public Nullable<System.DateTime> lastResLd { get; set; }
        public Nullable<System.DateTime> lastTktLd { get; set; }
        public Nullable<System.DateTime> lastCCLd { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
        public bool inactive { get; set; }
        public short loadPriority { get; set; }
        public string actualBackOff { get; set; }
        public string actBackOffVer { get; set; }
        public byte loadTravelOptix { get; set; }
        public Nullable<int> regionid { get; set; }
    }
}
