//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstragcy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mstragcy()
        {
            this.broadcast_stage_agencies = new HashSet<broadcast_stage_agencies>();
            this.broadcast_long_running_agencies = new HashSet<broadcast_long_running_agencies>();
            this.report_server_stage = new HashSet<report_server_stage>();
            this.report_rollout_stage = new HashSet<report_rollout_stage>();
            this.broadcast_high_alert_agency = new HashSet<broadcast_high_alert_agency>();
        }
    
        public string agency { get; set; }
        public string agencyname { get; set; }
        public string pathname { get; set; }
        public string databasename { get; set; }
        public string abbrev { get; set; }
        public bool active { get; set; }
        public Nullable<bool> bcactive { get; set; }
        public Nullable<System.DateTime> lastpack { get; set; }
        public Nullable<System.DateTime> lasttblupd { get; set; }
        public Nullable<short> tblupdfreq { get; set; }
        public bool lockout { get; set; }
        public string travelurl { get; set; }
        public string reservaurl { get; set; }
        public string agencylogo { get; set; }
        public string rptlogo { get; set; }
        public string reasexclude { get; set; }
        public Nullable<int> tzoffset { get; set; }
        public string bcsenderemail { get; set; }
        public string bcsendername { get; set; }
        public bool ticketbank { get; set; }
        public string agcyaddr1 { get; set; }
        public string agcyaddr2 { get; set; }
        public string agcyaddr3 { get; set; }
        public string agcyaddr4 { get; set; }
        public string profilesemailaddr { get; set; }
        public string profilesemailsender { get; set; }
        public bool servicefees { get; set; }
        public Nullable<int> keeppreviewdays { get; set; }
        public string iatanum { get; set; }
        public Nullable<bool> itractive { get; set; }
        public Nullable<bool> jetalertactive { get; set; }
        public string cisacct { get; set; }
        public Nullable<byte> securityapplied { get; set; }
        public Nullable<byte> numberofstrikes { get; set; }
        public Nullable<bool> transactional { get; set; }
        public System.DateTime InstallDate { get; set; }
        public Nullable<System.DateTime> transactivated { get; set; }
        public int transperqtr { get; set; }
        public byte ChangeMgmt { get; set; }
        public string ClientURL { get; set; }
        public string ibankversion { get; set; }
        public bool TravelAuth { get; set; }
        public bool AllowCurrConv { get; set; }
        public bool eFFECTS { get; set; }
        public string GICSC { get; set; }
        public string specialUse1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<broadcast_stage_agencies> broadcast_stage_agencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<broadcast_long_running_agencies> broadcast_long_running_agencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_server_stage> report_server_stage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_rollout_stage> report_rollout_stage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<broadcast_high_alert_agency> broadcast_high_alert_agency { get; set; }
    }
}
