//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstrAgcySourceExtras
    {
        public int recordNo { get; set; }
        public string agency { get; set; }
        public string sourceAbbr { get; set; }
        public string fieldFunction { get; set; }
        public string fieldData { get; set; }
    }
}
