//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class picklist
    {
        public int recordnum { get; set; }
        public string listname { get; set; }
        public string listtype { get; set; }
        public Nullable<int> usernumber { get; set; }
        public string agency { get; set; }
        public Nullable<System.DateTime> lastused { get; set; }
        public string listdata { get; set; }
    }
}
