//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomtype
    {
        public int RecordNo { get; set; }
        public string LangCode { get; set; }
        public string roomtype1 { get; set; }
        public string typedesc { get; set; }
        public string FullDesc { get; set; }
    }
}
