//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class RROperators
    {
        public int rrOperNbr { get; set; }
        public string rrOperCode { get; set; }
        public string rrOperName { get; set; }
        public string homeCtry { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> effStart { get; set; }
        public Nullable<System.DateTime> effEnd { get; set; }
    }
}
