//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class savedrpt1
    {
        public int recordnum { get; set; }
        public int usernumber { get; set; }
        public string agency { get; set; }
        public Nullable<short> processkey { get; set; }
        public string userrptnam { get; set; }
        public Nullable<int> udrkey { get; set; }
        public Nullable<System.DateTime> lastused { get; set; }
        public string srlongdesc { get; set; }
        public int travetLink { get; set; }
        public bool defaultInd { get; set; }
    }
}
