//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class savedrpt3
    {
        public int recordlink { get; set; }
        public int usernumber { get; set; }
        public string agency { get; set; }
        public Nullable<int> rowsequence { get; set; }
        public string colname { get; set; }
        public string oper { get; set; }
        public string value1 { get; set; }
        public string value1a { get; set; }
        public int recordno { get; set; }
    }
}
