//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvrStatus
    {
        public string SvrName { get; set; }
        public string SvrDesc { get; set; }
        public string SvrVer { get; set; }
        public System.DateTime SvrDateTm { get; set; }
        public Nullable<System.DateTime> LastCheck { get; set; }
        public string TimeSince { get; set; }
        public string LastStatus { get; set; }
        public bool CheckFlag { get; set; }
        public byte SortOrder { get; set; }
        public string FromServer { get; set; }
        public bool WroteToLog { get; set; }
        public string server_type { get; set; }
        public string machine_name { get; set; }
        public Nullable<System.DateTime> last_started { get; set; }
        public Nullable<int> server_number { get; set; }
        public Nullable<bool> currently_running { get; set; }
        public bool in_maintenance_mode { get; set; }
        public bool maintenance_mode_requested { get; set; }
    }
}
