//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradingPartners
    {
        public int TradingPartNo { get; set; }
        public string TradingPartName { get; set; }
        public string EntityName { get; set; }
        public string outbox { get; set; }
    }
}
