//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class transtrack
    {
        public int recordnum { get; set; }
        public string agency { get; set; }
        public string acct { get; set; }
        public string source { get; set; }
        public Nullable<short> year { get; set; }
        public Nullable<byte> month { get; set; }
        public string category { get; set; }
        public Nullable<int> catcount { get; set; }
        public string SourceAbbr { get; set; }
        public string PrelimFinal { get; set; }
    }
}
