//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTranslations
    {
        public int recordNo { get; set; }
        public string agency { get; set; }
        public int usernumber { get; set; }
        public int taglink { get; set; }
        public string langcode { get; set; }
        public string translatn { get; set; }
    }
}
