//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class userrpt2
    {
        public int reportkey { get; set; }
        public string agency { get; set; }
        public string crname { get; set; }
        public int UserNumber { get; set; }
        public string colname { get; set; }
        public short colorder { get; set; }
        public Nullable<short> sort { get; set; }
        public Nullable<short> grpbreak { get; set; }
        public bool subtotal { get; set; }
        public bool pagebreak { get; set; }
        public string udidhdg1 { get; set; }
        public string udidhdg2 { get; set; }
        public Nullable<int> udidwidth { get; set; }
        public int recordno { get; set; }
        public short udidtype { get; set; }
        public string horAlign { get; set; }
        public string goodfld { get; set; }
        public string goodoper { get; set; }
        public string goodvalue { get; set; }
        public string goodhilite { get; set; }
        public string badfld { get; set; }
        public string badoper { get; set; }
        public string badvalue { get; set; }
        public string badhilite { get; set; }
    }
}
