//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        public int recordNo { get; set; }
        public string agency { get; set; }
        public string vendorCode { get; set; }
        public string vendorDesc { get; set; }
        public string clientID { get; set; }
        public Nullable<int> vendorGrp { get; set; }
    }
}
