//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBank.Services.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class xmluserrpt
    {
        public int reportkey { get; set; }
        public string agency { get; set; }
        public string crname { get; set; }
        public int UserNumber { get; set; }
        public string crtype { get; set; }
        public string crtitle { get; set; }
        public string exportType { get; set; }
        public System.DateTime lastused { get; set; }
        public string xsdname { get; set; }
    }
}
