// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace iBank.UnitTesting.IBank_Services_Implementation.Utilities.ClientData
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class UdidFilterFeatureFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UdidFilterFeature.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "UdidFilterFeature", "\tIn order to filter records\r\n\tAs a user\r\n\tI need to filter my data based on UDID " +
                    "criteria", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "UdidFilterFeature")))
            {
                global::iBank.UnitTesting.IBank_Services_Implementation.Utilities.ClientData.UdidFilterFeatureFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("And Join All Equal Operators No Udids For Reckey Discard Record")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void AndJoinAllEqualOperatorsNoUdidsForReckeyDiscardRecord()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("And Join All Equal Operators No Udids For Reckey Discard Record", ((string[])(null)));
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 33
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
  testRunner.And("I have a join type of \'And\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
  testRunner.And("I have a udid record with a reckey \'99\' and udid number of \'10\' and udid text of " +
                    "\'foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
  testRunner.And("I have a udid record with a reckey \'99\' and udid number of \'11\' and udid text of " +
                    "\'bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.Then("the reckey \'1\' does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("And Join All Not Equal Operators No Udids For Reckey Retain")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void AndJoinAllNotEqualOperatorsNoUdidsForReckeyRetain()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("And Join All Not Equal Operators No Udids For Reckey Retain", ((string[])(null)));
#line 41
this.ScenarioSetup(scenarioInfo);
#line 42
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 43
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
  testRunner.And("I have a join type of \'And\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
  testRunner.And("I have a udid record with a reckey \'99\' and udid number of \'10\' and udid text of " +
                    "\'foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
  testRunner.And("I have a udid record with a reckey \'99\' and udid number of \'11\' and udid text of " +
                    "\'bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.Then("the reckey \'1\' does exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("And Join Mixed Equal Not Equal Operators No Udids For Reckey Discard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void AndJoinMixedEqualNotEqualOperatorsNoUdidsForReckeyDiscard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("And Join Mixed Equal Not Equal Operators No Udids For Reckey Discard", ((string[])(null)));
#line 51
this.ScenarioSetup(scenarioInfo);
#line 52
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 53
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
  testRunner.And("I have a join type of \'And\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
  testRunner.And("I have a udid record with a reckey \'99\' and udid number of \'10\' and udid text of " +
                    "\'foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
  testRunner.And("I have a udid record with a reckey \'99\' and udid number of \'11\' and udid text of " +
                    "\'bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
 testRunner.Then("the reckey \'1\' does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Or Join All Equal Operators No Udids For Reckey Discard Record")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void OrJoinAllEqualOperatorsNoUdidsForReckeyDiscardRecord()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Or Join All Equal Operators No Udids For Reckey Discard Record", ((string[])(null)));
#line 61
this.ScenarioSetup(scenarioInfo);
#line 62
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 63
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
  testRunner.And("I have a join type of \'Or\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
  testRunner.And("I have a udid record with a reckey \'99\' and udid number of \'10\' and udid text of " +
                    "\'foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
  testRunner.And("I have a udid record with a reckey \'99\' and udid number of \'11\' and udid text of " +
                    "\'bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 69
 testRunner.Then("the reckey \'1\' does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Or Join All Not Equal Operators No Udids For Reckey Retain")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void OrJoinAllNotEqualOperatorsNoUdidsForReckeyRetain()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Or Join All Not Equal Operators No Udids For Reckey Retain", ((string[])(null)));
#line 71
this.ScenarioSetup(scenarioInfo);
#line 72
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 73
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
  testRunner.And("I have a join type of \'Or\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
  testRunner.And("I have a udid record with a reckey \'99\' and udid number of \'10\' and udid text of " +
                    "\'foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
  testRunner.And("I have a udid record with a reckey \'99\' and udid number of \'11\' and udid text of " +
                    "\'bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 79
 testRunner.Then("the reckey \'1\' does exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Or Join Mixed Equal Not Equal Operators No Udids For Reckey Retain")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void OrJoinMixedEqualNotEqualOperatorsNoUdidsForReckeyRetain()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Or Join Mixed Equal Not Equal Operators No Udids For Reckey Retain", ((string[])(null)));
#line 81
this.ScenarioSetup(scenarioInfo);
#line 82
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 83
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
  testRunner.And("I have a join type of \'Or\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 86
  testRunner.And("I have a udid record with a reckey \'99\' and udid number of \'10\' and udid text of " +
                    "\'foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
  testRunner.And("I have a udid record with a reckey \'99\' and udid number of \'11\' and udid text of " +
                    "\'bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
 testRunner.Then("the reckey \'1\' does exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("And Join All Equal Operators Udids For Reckey Udid Filter Number Does Not Match D" +
            "iscard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void AndJoinAllEqualOperatorsUdidsForReckeyUdidFilterNumberDoesNotMatchDiscard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("And Join All Equal Operators Udids For Reckey Udid Filter Number Does Not Match D" +
                    "iscard", ((string[])(null)));
#line 95
this.ScenarioSetup(scenarioInfo);
#line 96
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 97
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
  testRunner.And("I have a join type of \'And\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'99\' and udid text of \'" +
                    "foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 101
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'100\' and udid text of " +
                    "\'bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 102
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 103
 testRunner.Then("the reckey \'1\' does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("And Join All Not Equal Operators Udids For Reckey Udid Filter Number Does Not Mat" +
            "ch Retain")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void AndJoinAllNotEqualOperatorsUdidsForReckeyUdidFilterNumberDoesNotMatchRetain()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("And Join All Not Equal Operators Udids For Reckey Udid Filter Number Does Not Mat" +
                    "ch Retain", ((string[])(null)));
#line 105
this.ScenarioSetup(scenarioInfo);
#line 106
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 107
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 109
  testRunner.And("I have a join type of \'And\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 110
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'99\' and udid text of \'" +
                    "foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 111
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'100\' and udid text of " +
                    "\'bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 112
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 113
 testRunner.Then("the reckey \'1\' does exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("And Join Mixed Equal Not Equal Operators Udids For Reckey Udid Filter Number Does" +
            " Not Match Discard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void AndJoinMixedEqualNotEqualOperatorsUdidsForReckeyUdidFilterNumberDoesNotMatchDiscard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("And Join Mixed Equal Not Equal Operators Udids For Reckey Udid Filter Number Does" +
                    " Not Match Discard", ((string[])(null)));
#line 115
this.ScenarioSetup(scenarioInfo);
#line 116
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 117
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 118
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 119
  testRunner.And("I have a join type of \'And\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 120
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'99\' and udid text of \'" +
                    "foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 121
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'100\' and udid text of " +
                    "\'bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 122
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 123
 testRunner.Then("the reckey \'1\' does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Or Join All Equal Operators Udids For Reckey Udid Filter Number Does Not Match Di" +
            "scard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void OrJoinAllEqualOperatorsUdidsForReckeyUdidFilterNumberDoesNotMatchDiscard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Or Join All Equal Operators Udids For Reckey Udid Filter Number Does Not Match Di" +
                    "scard", ((string[])(null)));
#line 125
this.ScenarioSetup(scenarioInfo);
#line 126
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 127
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 128
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 129
  testRunner.And("I have a join type of \'Or\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 130
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'99\' and udid text of \'" +
                    "foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 131
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'100\' and udid text of " +
                    "\'bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 132
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 133
 testRunner.Then("the reckey \'1\' does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Or Join All Not Equal Operators Udids For Reckey Udid Filter Number Does Not Matc" +
            "h Retain")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void OrJoinAllNotEqualOperatorsUdidsForReckeyUdidFilterNumberDoesNotMatchRetain()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Or Join All Not Equal Operators Udids For Reckey Udid Filter Number Does Not Matc" +
                    "h Retain", ((string[])(null)));
#line 135
this.ScenarioSetup(scenarioInfo);
#line 136
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 137
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 138
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 139
  testRunner.And("I have a join type of \'Or\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 140
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'99\' and udid text of \'" +
                    "foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 141
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'100\' and udid text of " +
                    "\'bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 142
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 143
 testRunner.Then("the reckey \'1\' does exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Or Join Mixed Equal Not Equal Operators Udids For Reckey Udid Filter Number Does " +
            "Not Match Retain")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void OrJoinMixedEqualNotEqualOperatorsUdidsForReckeyUdidFilterNumberDoesNotMatchRetain()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Or Join Mixed Equal Not Equal Operators Udids For Reckey Udid Filter Number Does " +
                    "Not Match Retain", ((string[])(null)));
#line 145
this.ScenarioSetup(scenarioInfo);
#line 146
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 147
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 148
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 149
  testRunner.And("I have a join type of \'Or\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 150
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'99\' and udid text of \'" +
                    "foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 151
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'100\' and udid text of " +
                    "\'bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 152
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 153
 testRunner.Then("the reckey \'1\' does exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("And Join All Equal Operators Udids For Reckey Udid Filter Number Does Match Udid " +
            "Filter Text Does Not Match Discard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void AndJoinAllEqualOperatorsUdidsForReckeyUdidFilterNumberDoesMatchUdidFilterTextDoesNotMatchDiscard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("And Join All Equal Operators Udids For Reckey Udid Filter Number Does Match Udid " +
                    "Filter Text Does Not Match Discard", ((string[])(null)));
#line 159
this.ScenarioSetup(scenarioInfo);
#line 160
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 161
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 163
  testRunner.And("I have a join type of \'And\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 164
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'10\' and udid text of \'" +
                    "blah\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 165
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'11\' and udid text of \'" +
                    "blah\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 166
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 167
 testRunner.Then("the reckey \'1\' does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("And Join All Not Equal Operators Udids For Reckey Udid Filter Number Does Match U" +
            "did Filter Text Does Not Match Retain")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void AndJoinAllNotEqualOperatorsUdidsForReckeyUdidFilterNumberDoesMatchUdidFilterTextDoesNotMatchRetain()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("And Join All Not Equal Operators Udids For Reckey Udid Filter Number Does Match U" +
                    "did Filter Text Does Not Match Retain", ((string[])(null)));
#line 169
this.ScenarioSetup(scenarioInfo);
#line 170
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 171
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 172
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 173
  testRunner.And("I have a join type of \'And\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 174
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'10\' and udid text of \'" +
                    "blah\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 175
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'11\' and udid text of \'" +
                    "blah\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 176
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 177
 testRunner.Then("the reckey \'1\' does exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("And Join Mixed Equal Not Equal Operators Udids For Reckey Udid Filter Number Does" +
            " Match Udid Filter Text Does Not Match Discard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void AndJoinMixedEqualNotEqualOperatorsUdidsForReckeyUdidFilterNumberDoesMatchUdidFilterTextDoesNotMatchDiscard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("And Join Mixed Equal Not Equal Operators Udids For Reckey Udid Filter Number Does" +
                    " Match Udid Filter Text Does Not Match Discard", ((string[])(null)));
#line 179
this.ScenarioSetup(scenarioInfo);
#line 180
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 181
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 182
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 183
  testRunner.And("I have a join type of \'And\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 184
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'10\' and udid text of \'" +
                    "blah\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 185
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'11\' and udid text of \'" +
                    "blah\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 186
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 187
 testRunner.Then("the reckey \'1\' does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Or Join All Equal Operators Udids For Reckey Udid Filter Number Does Match Udid F" +
            "ilter Text Does Not Match Discard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void OrJoinAllEqualOperatorsUdidsForReckeyUdidFilterNumberDoesMatchUdidFilterTextDoesNotMatchDiscard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Or Join All Equal Operators Udids For Reckey Udid Filter Number Does Match Udid F" +
                    "ilter Text Does Not Match Discard", ((string[])(null)));
#line 189
this.ScenarioSetup(scenarioInfo);
#line 190
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 191
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 192
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 193
  testRunner.And("I have a join type of \'Or\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 194
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'10\' and udid text of \'" +
                    "blah\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 195
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'11\' and udid text of \'" +
                    "blah\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 196
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 197
 testRunner.Then("the reckey \'1\' does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Or Join All Not Equal Operators Udids For Reckey Udid Filter Number Does Match Ud" +
            "id Filter Text Does Not Match Retain")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void OrJoinAllNotEqualOperatorsUdidsForReckeyUdidFilterNumberDoesMatchUdidFilterTextDoesNotMatchRetain()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Or Join All Not Equal Operators Udids For Reckey Udid Filter Number Does Match Ud" +
                    "id Filter Text Does Not Match Retain", ((string[])(null)));
#line 199
this.ScenarioSetup(scenarioInfo);
#line 200
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 201
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 202
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 203
  testRunner.And("I have a join type of \'Or\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 204
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'10\' and udid text of \'" +
                    "blah\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 205
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'11\' and udid text of \'" +
                    "blah\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 206
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 207
 testRunner.Then("the reckey \'1\' does exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Or Join Mixed Equal Not Equal Operators Udids For Reckey Udid Filter Number Does " +
            "Match Udid Filter Text Does Not Match Retain")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void OrJoinMixedEqualNotEqualOperatorsUdidsForReckeyUdidFilterNumberDoesMatchUdidFilterTextDoesNotMatchRetain()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Or Join Mixed Equal Not Equal Operators Udids For Reckey Udid Filter Number Does " +
                    "Match Udid Filter Text Does Not Match Retain", ((string[])(null)));
#line 209
this.ScenarioSetup(scenarioInfo);
#line 210
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 211
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 212
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 213
  testRunner.And("I have a join type of \'Or\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 214
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'10\' and udid text of \'" +
                    "blah\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 215
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'11\' and udid text of \'" +
                    "blah\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 216
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 217
 testRunner.Then("the reckey \'1\' does exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("And Join All Equal Operators Udids For Reckey Udid Filter Number Does Match Udid " +
            "Filter Text Does Match Retain")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void AndJoinAllEqualOperatorsUdidsForReckeyUdidFilterNumberDoesMatchUdidFilterTextDoesMatchRetain()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("And Join All Equal Operators Udids For Reckey Udid Filter Number Does Match Udid " +
                    "Filter Text Does Match Retain", ((string[])(null)));
#line 223
this.ScenarioSetup(scenarioInfo);
#line 224
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 225
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 226
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 227
  testRunner.And("I have a join type of \'And\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 228
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'10\' and udid text of \'" +
                    "foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 229
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'11\' and udid text of \'" +
                    "bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 230
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 231
 testRunner.Then("the reckey \'1\' does exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("And Join All Not Equal Operators Udids For Reckey Udid Filter Number Does Match U" +
            "did Filter Text Does Match Discard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void AndJoinAllNotEqualOperatorsUdidsForReckeyUdidFilterNumberDoesMatchUdidFilterTextDoesMatchDiscard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("And Join All Not Equal Operators Udids For Reckey Udid Filter Number Does Match U" +
                    "did Filter Text Does Match Discard", ((string[])(null)));
#line 233
this.ScenarioSetup(scenarioInfo);
#line 234
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 235
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 236
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 237
  testRunner.And("I have a join type of \'And\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 238
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'10\' and udid text of \'" +
                    "foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 239
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'11\' and udid text of \'" +
                    "bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 240
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 241
 testRunner.Then("the reckey \'1\' does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("And Join Mixed Equal Not Equal Operators Udids For Reckey Udid Filter Number Does" +
            " Match Udid Filter Text Does Match Discard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void AndJoinMixedEqualNotEqualOperatorsUdidsForReckeyUdidFilterNumberDoesMatchUdidFilterTextDoesMatchDiscard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("And Join Mixed Equal Not Equal Operators Udids For Reckey Udid Filter Number Does" +
                    " Match Udid Filter Text Does Match Discard", ((string[])(null)));
#line 243
this.ScenarioSetup(scenarioInfo);
#line 244
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 245
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 246
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 247
  testRunner.And("I have a join type of \'And\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 248
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'10\' and udid text of \'" +
                    "foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 249
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'11\' and udid text of \'" +
                    "bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 250
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 251
 testRunner.Then("the reckey \'1\' does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Or Join All Equal Operators Udids For Reckey Udid Filter Number Does Match Udid F" +
            "ilter Text Does Match Retain")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void OrJoinAllEqualOperatorsUdidsForReckeyUdidFilterNumberDoesMatchUdidFilterTextDoesMatchRetain()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Or Join All Equal Operators Udids For Reckey Udid Filter Number Does Match Udid F" +
                    "ilter Text Does Match Retain", ((string[])(null)));
#line 253
this.ScenarioSetup(scenarioInfo);
#line 254
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 255
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 256
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 257
  testRunner.And("I have a join type of \'Or\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 258
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'10\' and udid text of \'" +
                    "foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 259
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'11\' and udid text of \'" +
                    "bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 260
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 261
 testRunner.Then("the reckey \'1\' does exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Or Join All Not Equal Operators Udids For Reckey Udid Filter Number Does Match Ud" +
            "id Filter Text Does Match Discard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void OrJoinAllNotEqualOperatorsUdidsForReckeyUdidFilterNumberDoesMatchUdidFilterTextDoesMatchDiscard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Or Join All Not Equal Operators Udids For Reckey Udid Filter Number Does Match Ud" +
                    "id Filter Text Does Match Discard", ((string[])(null)));
#line 263
this.ScenarioSetup(scenarioInfo);
#line 264
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 265
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 266
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 267
  testRunner.And("I have a join type of \'Or\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 268
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'10\' and udid text of \'" +
                    "foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 269
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'11\' and udid text of \'" +
                    "bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 270
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 271
 testRunner.Then("the reckey \'1\' does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Or Join Mixed Equal Not Equal Operators Udids For Reckey Udid Filter Number Does " +
            "Match Udid Filter Text Does Match Retain")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UdidFilterFeature")]
        public virtual void OrJoinMixedEqualNotEqualOperatorsUdidsForReckeyUdidFilterNumberDoesMatchUdidFilterTextDoesMatchRetain()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Or Join Mixed Equal Not Equal Operators Udids For Reckey Udid Filter Number Does " +
                    "Match Udid Filter Text Does Match Retain", ((string[])(null)));
#line 273
this.ScenarioSetup(scenarioInfo);
#line 274
 testRunner.Given("I have a data record with a reckey of \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 275
  testRunner.And("I have a udid filter with a udid number of 10 and a udid text of \'foo\' and an ope" +
                    "rator of \'Equal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 276
  testRunner.And("I have a udid filter with a udid number of 11 and a udid text of \'bar\' and an ope" +
                    "rator of \'NotEqual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 277
  testRunner.And("I have a join type of \'Or\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 278
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'10\' and udid text of \'" +
                    "foo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 279
  testRunner.And("I have a udid record with a reckey \'1\' and udid number of \'11\' and udid text of \'" +
                    "bar\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 280
 testRunner.When("I filter the data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 281
 testRunner.Then("the reckey \'1\' does exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
